### ISSUE TITLE
Nested Dependency on `nodejs`preventing initial `vagrant up`

### ISSUE THREAD

**Issue by mikeselander** [Chassis/Debugging#10]
In the Version 2 configuration file, this extension now requires `yarn` as a dependency. however, `yarn` also requires `node.js` in it's configuration file. Upon upping for the first time, `node.js` is not installed and a variety of errors can be thrown:

**_Error 1:_**
```
==> default: Error: Could not find dependency Class[Nodejs] for Exec[install yarn] at /vagrant/extensions/yarn/modules/yarn/manifests/init.pp:17
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**_Error 2:_**
```
==> default: Error: Could not parse for environment production: No file(s) found for import of '/vagrant/extensions/*/chassis.pp' at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:4 on node vagrant.local
==> default: Error: Could not parse for environment production: No file(s) found for import of '/vagrant/extensions/*/chassis.pp' at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:4 on node vagrant.local
```

Either way, we end up with a botched install and a confused client :/ 

Example `config.yaml`:

```
# Establish our custom paths for local.
paths:
  base: ..
  content: content
  wp: wordpress

# Default domain to know..
hosts:
  - client.local

# Define database prefix, since we have tests as well.
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_

# Install a list of Chassis extensions automatically.
extensions:
  - Chassis/Cavalcade
  - Chassis/Debugging
  - Chassis/Memcache
  - Chassis/SequelPro
  - Chassis/Tester
  - Chassis/Xdebug

# PHP version.
php: 7.2

# Setup a predictable administrator to begin with.
admin:
  user: clientdev
  email: admin@example.com
  password: password

# Default our theme activated and turned on.
themes:
  - client
```
