### ISSUE TITLE
Plugins not installed when using non-standard content directory

### ISSUE THREAD

**Issue by mikeselander** [Chassis/Debugging#6]
When using the below directory setup and path routing, and activating the Debugging extension, the debugging plugins are neither pulled down locally nor installed.

```
 - /chassis (Everything Chassis)
   - config.local.yaml (Basic overrides
 - /content (Actual used content directory)
   - config.local.yaml (Installation-specific overrides)
 - /wordpress (WordPress used on platform)
```

```yml
paths:
  base: ..
  content: content
  wp: wordpress
```

The extension is defined in `/chassis/config.local.yaml`

**Comment by BronsonQuick** [comment]
@mikeselander Hey Sir! Sorry for the delay on this one. I just saw https://github.com/humanmade/hm-base/issues/73#issuecomment-433238128 and was looking into this. I have a project setup with the exact same setup as you have above.

```
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - client.local
multisite: true

# Define database prefix, since we have tests as well
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_
# Define the extensions we want
extensions:
    - chassis/xdebug
    - chassis/sequelpro
    - chassis/cavalcade
    - chassis/mailhog
    - chassis/composer
    - chassis/phpcs
    - chassis/mailhog
    - chassis/chassis-elasticsearch
    - chassis/intl
    - chassis/phpini
    - chassis/debugging
elasticsearch:
    version: '5.3.3'
composer:
    paths:
    - /chassis/content/plugins-mu/vendor/memcached-adapter
    - /chassis/content/plugins-mu/vendor/simple-cache-bridge
    - /chassis/content/plugins-mu/vendor/PhpSpreadsheet
disabled_extensions:
    - chassis/chassis-xhgui
php: 7.2
```

This installed and activated the plugins in the Debugging extension for me correctly.

Do you think I should maybe try it as a single site installation?

Could you please shoot me through all your configs with the client url changes or let me know what errors you see when you run `vagrant provision`? Thanks!
